version : '3'

services: 
    mdb:
        image: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "umarabox"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
        networks:
            - mynet
        volumes:
            - 
    

   

networks:
    musjibnet:
        driver: bridge